<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20220210134227" tests="4" file="unittest/loader.py" time="0.008" timestamp="2022-02-10T13:42:27" failures="0" errors="4" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="circle_tests" time="0.002" timestamp="2022-02-10T13:42:27">
		<error type="ImportError" message="Failed to import test module: circle_tests
Traceback (most recent call last):
  File &quot;c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\circle_tests.py&quot;, line 4, in &lt;module&gt;
    from src.main.python.physics_engine.circle import Circle
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: circle_tests
Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\circle_tests.py", line 4, in <module>
    from src.main.python.physics_engine.circle import Circle
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="rectangle_tests" time="0.002" timestamp="2022-02-10T13:42:27">
		<error type="ImportError" message="Failed to import test module: rectangle_tests
Traceback (most recent call last):
  File &quot;c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\rectangle_tests.py&quot;, line 9, in &lt;module&gt;
    from src.main.python.physics_engine.rectangle import Rectangle
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: rectangle_tests
Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\rectangle_tests.py", line 9, in <module>
    from src.main.python.physics_engine.rectangle import Rectangle
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="segment_tests" time="0.002" timestamp="2022-02-10T13:42:27">
		<error type="ImportError" message="Failed to import test module: segment_tests
Traceback (most recent call last):
  File &quot;c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\segment_tests.py&quot;, line 9, in &lt;module&gt;
    from src.main.python.physics_engine.segment import Segment
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: segment_tests
Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\segment_tests.py", line 9, in <module>
    from src.main.python.physics_engine.segment import Segment
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="triangle_tests" time="0.002" timestamp="2022-02-10T13:42:27">
		<error type="ImportError" message="Failed to import test module: triangle_tests
Traceback (most recent call last):
  File &quot;c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\triangle_tests.py&quot;, line 9, in &lt;module&gt;
    from src.main.python.physics_engine.triangle import Triangle
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: triangle_tests
Traceback (most recent call last):
  File "c:\users\thefastfamily\appdata\local\programs\python\python38\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\thefastfamily\nextcloud\beuth-myhome\m02 advanced softwareengineering\04 projects\sandbox_pycharm\src\unittest\python\triangle_tests.py", line 9, in <module>
    from src.main.python.physics_engine.triangle import Triangle
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
